version: '3.8'
services:
  app:
    image: express:1.0
    container_name: express
    restart: always
    build: 
      context: ./
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_URL=${DB_URL}
      - DB_USER=postgres
      - DB_PASS=${PGPASS}
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:15.1-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${PGPASS}
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${PGPATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432